#!/bin/bash

# Script Echo // Version Linux

<<"COMMENTS"
COMMENTS

# English version
# Copyright (C) 2023 BOUCARD NICOLLE Jody

# This file is part of AScripts.

# AScripts is free software: you can redistribute it and/or modify it under the terms of the GNU General 
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your 
# option) any later version.

# AScripts is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the 
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
# General Public License for more details.

# You should have received a copy of the GNU General Public License along with AScripts. If not, see 
# <https://www.gnu.org/licenses/>.


# Version française
# Copyright (C) 2023 BOUCARD NICOLLE Jody

# Ce fichier fait partie de AScripts.

# AScripts est un logiciel libre ; vous pouvez le redistribuer ou le modifier suivant les termes de la GNU General 
# Public License telle que publiée par la Free Software Foundation, soit la version 3 de la licence, soit (à votre 
# gré) toute version ultérieure.

# AScripts est distribué dans l'espoir qu'il sera utile, mais SANS AUCUNE GARANTIE; sans même la 
# garantie tacite de QUALITÉ MARCHANDE ou d'ADÉQUATION À UN BUT PARTICULIER. Consultez la GNU 
# General Public License pour plus de détails.

# Vous devez avoir reçu une copie de la GNU General Public License en même temps que AScripts. Si ce n'est pas le cas, consultez 
# <http://www.gnu.org/licenses>.

Type=true
Ret=false

declare -A colors

colors=([black]=0 [red]=1 [green]=2 [yellow]=3 [blue]=4 [magenta]=5 [cyan]=6 [white]=7 [default]=8)

if [ $# != 3 ]
then
    echo "You must specify exactly 3 parameters."
    exit 1
fi

for color in "${!colors[@]}"; do
    if [ $2 = $color ]; then
        Ret=true
    fi
done

if [ $Ret != true ]; then
    echo "Foreground color is invalid."
    exit 3
fi

for color in "${!colors[@]}"; do
    if [ $3 = $color ]; then
        Ret=true
    fi
done

if [ $Ret != true ]; then
    echo "Background color is invalid."
    exit 4
fi

if [ $2 != default ]
then
    tput setaf ${colors[$2]}
fi

if [ $3 != default ]
then
    tput setab ${colors[$3]}
fi

echo -e "$1"
tput sgr0

exit 0

